import { Router, type Router as ExpressRouter } from 'express';
import adminPedidoRoutes from './admin.pedido.routes';
import adminRealtimeRoutes from './admin.realtime.routes';
import adminClienteRoutes from './admin.cliente.routes';
import adminAlertaRoutes from './admin.alerta.routes';
import adminRelatorioRoutes from './admin.relatorio.routes';
import adminIaRoutes from './admin.ia.routes';
import adminMineracaoRoutes from './admin.mineracao.routes';
import adminEntregaRoutes from './admin.entrega.routes';
import adminPedidoController from '../controllers/admin.pedido.controller';
import { autenticarAdmin, autorizarAdmin, loginAdmin, refreshAdmin } from '../middlewares/adminAuth.middleware';
import { loginLimiter, adminLimiter } from '../middlewares/rateLimit.middleware';

const router: ExpressRouter = Router();

router.post('/auth/login', loginLimiter, loginAdmin);
router.post('/auth/refresh', autenticarAdmin, refreshAdmin);
router.use(adminLimiter);
router.use(autenticarAdmin);
router.use('/pedidos', adminPedidoRoutes);
router.use('/', adminRealtimeRoutes);
router.use('/', adminClienteRoutes);
router.use('/alertas', adminAlertaRoutes);
router.use('/relatorios', adminRelatorioRoutes);
router.use('/ia', adminIaRoutes);
router.use('/mineracao', adminMineracaoRoutes);
router.use('/entregas', adminEntregaRoutes);
router.get('/clientes/geo', autorizarAdmin('clientes:gerenciar'), adminPedidoController.clientesGeolocalizados.bind(adminPedidoController));
router.get('/fila-urgente', autorizarAdmin('pedidos:ler'), adminPedidoController.filaUrgente.bind(adminPedidoController));
router.get('/metricas', autorizarAdmin('metricas:ler'), adminPedidoController.metricas.bind(adminPedidoController));
router.get('/motoboys/status', autorizarAdmin('pedidos:ler'), adminPedidoController.statusMotoboys.bind(adminPedidoController));
router.get('/motoboys', autorizarAdmin('pedidos:ler'), adminPedidoController.listarMotoboys.bind(adminPedidoController));
router.post('/motoboys', autorizarAdmin('pedidos:motoboy'), adminPedidoController.criarMotoboy.bind(adminPedidoController));
router.patch('/motoboys/:id', autorizarAdmin('pedidos:motoboy'), adminPedidoController.atualizarMotoboy.bind(adminPedidoController));
router.get('/motoboys/:id/acerto', autorizarAdmin('pedidos:ler'), adminPedidoController.acertoMotoboy.bind(adminPedidoController));
router.get('/loja/status', autorizarAdmin('loja:gerenciar'), adminPedidoController.obterStatusLoja.bind(adminPedidoController));
router.patch('/loja/status', autorizarAdmin('loja:gerenciar'), adminPedidoController.atualizarStatusLoja.bind(adminPedidoController));
router.get('/loja/localizacao', autorizarAdmin('loja:gerenciar'), adminPedidoController.obterLocalizacaoLoja.bind(adminPedidoController));
router.patch('/loja/localizacao', autorizarAdmin('loja:gerenciar'), adminPedidoController.atualizarLocalizacaoLoja.bind(adminPedidoController));
router.get('/pagamentos/mercadopago', autorizarAdmin('loja:gerenciar'), adminPedidoController.obterConfiguracaoMercadoPago.bind(adminPedidoController));
router.patch('/pagamentos/mercadopago', autorizarAdmin('loja:gerenciar'), adminPedidoController.atualizarConfiguracaoMercadoPago.bind(adminPedidoController));
router.get('/loja/faixas-entrega', autorizarAdmin('loja:gerenciar'), adminPedidoController.obterFaixasEntrega.bind(adminPedidoController));
router.put('/loja/faixas-entrega', autorizarAdmin('loja:gerenciar'), adminPedidoController.salvarFaixasEntrega.bind(adminPedidoController));

export default router;
